events{}


http {
    upstream apigateway {
        server app1:4500;
        server app2:4501;
        server app3:4503;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://apigateway;
        }
    }
}